#[repr(u32)]
pub enum ContractError {
    SwapNotFound = 1,
    InvalidKey = 2,
    PriceMustBeGreaterThanZero = 3,
    SellerIsNotTheIPOwner = 4,
    ActiveSwapAlreadyExistsForThisIpId = 5,
    SwapNotPending = 6,
    OnlyTheSellerCanRevealTheKey = 7,
    SwapNotAccepted = 8,
    OnlyTheSellerOrBuyerCanCancel = 9,
    OnlyPendingSwapsCanBeCancelledThisWay = 10,
    SwapNotInAcceptedState = 11,
    OnlyTheBuyerCanCancelAnExpiredSwap = 12,
    SwapHasNotExpiredYet = 13,
    IpIsRevoked = 14,
    UnauthorizedUpgrade = 15,
    InvalidFeeBps = 16,
    DisputeWindowExpired = 17,
    OnlyBuyerCanDispute = 18,
    SwapNotDisputed = 19,
    OnlyAdminCanResolve = 20,
    AlreadyInitialized = 21,
    NotInitialized = 22,
    ContractPaused = 23,
    Unauthorized = 24,
}
